#!/bin/bash

# Script to generate localnet ConfigMaps from downloaded files
# Run download-localnet-files.sh first

set -e

LOCAL_DIR="../localnet-files"
OUTPUT_FILE="../canopy/canopy-localnet-genesis-keys.yaml"

if [ ! -d "$LOCAL_DIR" ]; then
    echo "❌ Error: $LOCAL_DIR directory not found"
    echo "Please run ./scripts/download-localnet-files.sh first"
    exit 1
fi

echo "🔧 Generating localnet ConfigMaps..."

# Create temp file for genesis and keys ConfigMaps
TEMP_FILE=$(mktemp)
cat > "$TEMP_FILE" << 'EOF'
# Localnet Genesis and Keys ConfigMaps
# This file is generated by generate-localnet-configmaps.sh
# It includes genesis.json and validator keys/keystores for 3 nodes
# The config template is in canopy-localnet-configmaps.yaml
EOF

# Append genesis ConfigMap
echo "" >> "$TEMP_FILE"
echo "---" >> "$TEMP_FILE"
cat >> "$TEMP_FILE" << 'EOF'
apiVersion: v1
kind: ConfigMap
metadata:
  name: canopy-localnet-genesis
  namespace: canopy-localnet
data:
EOF

# Add genesis.json
if [ -f "$LOCAL_DIR/genesis.json" ]; then
    echo "  genesis.json: |" >> "$TEMP_FILE"
    sed 's/^/    /' "$LOCAL_DIR/genesis.json" >> "$TEMP_FILE"
else
    echo "⚠️  Warning: genesis.json not found, creating placeholder"
    cat >> "$TEMP_FILE" << 'GENESIS_EOF'
  genesis.json: |
    {
      "time": "2024-01-01 00:00:00",
      "accounts": [],
      "validators": [],
      "params": {}
    }
GENESIS_EOF
fi

# Create ConfigMaps for each node's validator key and keystore
for node_num in 1 2 3; do
    echo "" >> "$TEMP_FILE"
    echo "---" >> "$TEMP_FILE"
    cat >> "$TEMP_FILE" << EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: canopy-localnet-node${node_num}-validator-key
  namespace: canopy-localnet
data:
EOF
    
    if [ -f "$LOCAL_DIR/node${node_num}_validator_key.json" ]; then
        echo "  validator_key.json: |" >> "$TEMP_FILE"
        sed 's/^/    /' "$LOCAL_DIR/node${node_num}_validator_key.json" >> "$TEMP_FILE"
    else
        echo "⚠️  Warning: validator_key.json not found for node${node_num}, creating placeholder"
        cat >> "$TEMP_FILE" << VALIDATOR_EOF
  validator_key.json: |
    {
      "address": "placeholder_node${node_num}",
      "publicKey": "placeholder_public_key_node${node_num}"
    }
VALIDATOR_EOF
    fi
    
    echo "" >> "$TEMP_FILE"
    echo "---" >> "$TEMP_FILE"
    cat >> "$TEMP_FILE" << EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: canopy-localnet-node${node_num}-keystore
  namespace: canopy-localnet
data:
EOF
    
    if [ -f "$LOCAL_DIR/node${node_num}_keystore.json" ]; then
        echo "  keystore.json: |" >> "$TEMP_FILE"
        sed 's/^/    /' "$LOCAL_DIR/node${node_num}_keystore.json" >> "$TEMP_FILE"
    else
        echo "⚠️  Warning: keystore.json not found for node${node_num}, creating placeholder"
        cat >> "$TEMP_FILE" << KEYSTORE_EOF
  keystore.json: |
    {
      "address": "placeholder_node${node_num}",
      "crypto": {
        "cipher": "aes-128-ctr",
        "ciphertext": "placeholder"
      }
    }
KEYSTORE_EOF
    fi
done

# Move temp file to final output
mv "$TEMP_FILE" "$OUTPUT_FILE"

echo "✅ ConfigMaps generated in: $OUTPUT_FILE"
echo "You can now apply it with: kubectl apply -f ../canopy/canopy-localnet-configmaps.yaml -f $OUTPUT_FILE"
echo "Or use: make localnet-configmaps"

