#!/bin/bash

# Scale Canopy Nodes Script
set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to generate service YAML for a node
generate_service() {
    local node_num=$1
    cat << EOF
---
apiVersion: v1
kind: Service
metadata:
  name: node${node_num}
  namespace: canopy
spec:
  selector:
    app: canopy-node
    statefulset.kubernetes.io/pod-name: canopy-node-$((node_num-1))
  ports:
  - name: wallet
    port: 50000
    targetPort: 50000
  - name: explorer
    port: 50001
    targetPort: 50001
  - name: rpc
    port: 50002
    targetPort: 50002
  - name: admin-rpc
    port: 50003
    targetPort: 50003
  - name: p2p
    port: 9001
    targetPort: 9001
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
EOF
}

# Check if kubectl is available
if ! command -v kubectl &> /dev/null; then
    print_error "kubectl is not installed or not in PATH"
    exit 1
fi

# Check if cluster is accessible
if ! kubectl cluster-info &> /dev/null; then
    print_error "Cannot connect to Kubernetes cluster"
    exit 1
fi

# Check if number of replicas is provided
if [ $# -eq 0 ]; then
    print_warning "No number of replicas provided. Using default of 3."
    REPLICAS=3
else
    REPLICAS=$1
fi

# Validate input
if ! [[ "$REPLICAS" =~ ^[0-9]+$ ]] || [ "$REPLICAS" -lt 1 ] || [ "$REPLICAS" -gt 15 ]; then
    print_error "Invalid number of replicas. Must be a positive integer between 1 and 15."
    exit 1
fi

print_status "Connected to Kubernetes cluster: $(kubectl config current-context)"
print_status "Scaling canopy nodes to $REPLICAS replicas..."

# Check if canopy namespace exists
if ! kubectl get namespace canopy &> /dev/null; then
    print_error "Canopy namespace does not exist. Please deploy the canopy stack first."
    exit 1
fi

# Check if StatefulSet exists
if ! kubectl get statefulset canopy-node -n canopy &> /dev/null; then
    print_error "Canopy StatefulSet does not exist. Please deploy the canopy stack first."
    exit 1
fi

# Get current replicas
CURRENT_REPLICAS=$(kubectl get statefulset canopy-node -n canopy -o jsonpath='{.spec.replicas}')
print_status "Current replicas: $CURRENT_REPLICAS"

# Generate services for all nodes
print_status "Generating services for $REPLICAS canopy nodes..."

# Create services file
SERVICES_FILE="canopy-services-scaled.yaml"

# Clear the file and add header
cat > "$SERVICES_FILE" << EOF
# Generated services for scaled canopy nodes
# This file is automatically generated by scale-canopy.sh
# Generated on: $(date)
# Number of replicas: $REPLICAS
EOF

# Generate services for each node
for i in $(seq 1 $REPLICAS); do
    print_status "Generating service for node$i..."
    generate_service $i >> "$SERVICES_FILE"
done

print_status "Generated $REPLICAS services in $SERVICES_FILE"

# Apply the services
print_status "Applying services to Kubernetes cluster..."
kubectl apply -f "$SERVICES_FILE"

# Scale the StatefulSet
print_status "Scaling StatefulSet to $REPLICAS replicas..."
kubectl scale statefulset canopy-node --replicas=$REPLICAS -n canopy

print_status "Scaling completed successfully!"
print_status "You can monitor the scaling progress with:"
echo "kubectl get pods -n canopy -w"
echo ""
print_status "Services available:"
for i in $(seq 1 $REPLICAS); do
    echo "  Node $i: node$i.canopy.svc.cluster.local"
done

echo ""
print_status "Direct pod access (headless service):"
for i in $(seq 1 $REPLICAS); do
    echo "  Pod $((i-1)): canopy-node-$((i-1)).canopy-node-headless.canopy.svc.cluster.local"
done

echo ""
print_status "Port forward examples:"
for i in $(seq 1 $REPLICAS); do
    echo "  Node $i RPC: kubectl port-forward service/node$i 5000$i:50002 -n canopy"
done

echo ""
print_status "Load balanced access:"
echo "  RPC: kubectl port-forward service/canopy-node 50002:50002 -n canopy"
echo "  Wallet: kubectl port-forward service/canopy-node 50000:50000 -n canopy"
echo "  Explorer: kubectl port-forward service/canopy-node 50001:50001 -n canopy"

echo ""
print_status "To check logs for a specific node:"
for i in $(seq 1 $REPLICAS); do
    echo "  Node $i: kubectl logs -f canopy-node-$((i-1)) -n canopy"
done

echo ""
print_status "To clean up scaled resources:"
echo "kubectl delete -f $SERVICES_FILE"
echo "kubectl scale statefulset canopy-node --replicas=3 -n canopy"

echo ""
print_status "Services file saved as: $SERVICES_FILE"
print_status "You can reuse this file for future deployments with the same number of replicas." 