
x-loki:
  &loki-logging
  driver: loki
  options:
    loki-url: "http://localhost:3100/loki/api/v1/push"
    max-size: 5m
    mode: non-blocking
    max-buffer-size: 4m
    loki-retries: '3'
    max-file: '3'
    keep-file: 'false'

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil
    ports:
      - 8545:8545
    entrypoint: ["anvil", "-vvv", "--chain-id", "1", "--host", "0.0.0.0", "--block-time", "2", "--port", "8545"]
    volumes:
      - ./anvil:/anvil
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  anvil-init:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil-init
    user: "0"
    depends_on:
      - anvil
    entrypoint: ["/anvil/anvil.sh"]
    volumes:
      - ./anvil:/anvil
    working_dir: /anvil
  node1:
    container_name: node1
    hostname: node1
    build:
      context: ../docker_image
      dockerfile: ./Dockerfile
      network: host
      args:
        EXPLORER_BASE_PATH: '/'
        WALLET_BASE_PATH: '/'
        BUILD_PATH: cmd/cli
        BIN_PATH: $BIN_PATH
        BRANCH: eth-oracle
    env_file:
      - .env
    ports:
      - 9001:9001 # TCP P2P
    expose:
      - 50000 # Wallet
      - 50001 # Explorer
      - 50002 # RPC
      - 50003 # Admin RPC
    command: [ "start" ]
    volumes:
      - ../canopy_data/node1:/root/.canopy
      # - ../docker_image/entrypoint.sh:/app/entrypoint.sh
    logging: *loki-logging
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
  node2:
    container_name: node2
    hostname: node2
    build:
      context: ../docker_image
      dockerfile: ./Dockerfile
      network: host
      args:
        EXPLORER_BASE_PATH: '/'
        WALLET_BASE_PATH: '/'
        BUILD_PATH: cmd/cli
        BIN_PATH: $BIN_PATH
        BRANCH: eth-oracle
    environment:
      - ETH_RPC_URL=http://anvil:8545
      - E2E_FROM_NICK=nick-0
      - E2E_FROM_PASS=test
      - USDC_CONTRACT=0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9
    env_file:
      - .env
    ports:
      - 9002:9002 # TCP P2P
    expose:
      - 40000 # Wallet
      - 40001 # Explorer
      - 40002 # RPC
      - 40003 # Admin RPC
    command: [ "start" ]
    volumes:
      - ../canopy_data/node2:/root/.canopy
    logging: *loki-logging
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
  oracle-e2e:
    container_name: oracle-e2e
    hostname: oracle-e2e
    build:
      context: ../docker_image
      dockerfile: ./e2e.Dockerfile
      network: host
      args:
        BRANCH: eth-oracle
    environment:
      - ETH_RPC_URL=http://anvil:8545
      - E2E_FROM_NICK=nick-0
      - E2E_FROM_PASS=test
      - USDC_CONTRACT=0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9
    env_file:
      - .env
    command: [ "start" ]
    volumes:
      - ../canopy_data/node1:/root/.canopy
    logging: *loki-logging
    deploy:
      resources:
        limits:
          memory: 400m
          cpus: "0.5"

  traefik:
    cpus: 2
    mem_limit: 2G
    image: traefik:latest
    container_name: traefik
    restart: always
    env_file: 
      - .env
    ports:
      - 80:80
      - 443:443 
      - 8082 # metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./loadbalancer/traefik.yml:/traefik.yml:ro
      - ./loadbalancer/services/:/etc/traefik/services/:ro
      - ./loadbalancer/certs:/letsencrypt
    logging: *loki-logging

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/data:/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    restart: always
    logging: *loki-logging


  grafana:
    image: grafana/grafana:latest
    container_name: grafana 
    user: root
    ports:
    -  "3000:3000"
    volumes:
      - ./monitoring/grafana/data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file: 
      - .env
    restart: always
    logging: *loki-logging

  loki:
    image: grafana/loki:3.4.4
    container_name: loki
    volumes:
      - ./monitoring/loki/config.yaml:/etc/loki/local-config.yaml
      - ./monitoring/loki/data:/data/loki
    expose:
      - 3100
    ports:
      - "3100:3100" 
    command: --config.file=/etc/loki/local-config.yaml
    restart: always
    logging: *loki-logging

  blackbox:
    container_name: blackbox
    image: prom/blackbox-exporter:latest
    privileged: true
    expose:
      - '9115'  
    volumes:
      - ./monitoring/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter 
    expose:
      - 9100 
    restart: always
    logging: *loki-logging
