log:
  level:  INFO 

MaxIdleConnsPerHost: 400000 

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

ping:
  entryPoint: "ping"
  manualRouting: true
  terminatingStatusCode: 200

api:
  dashboard: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":8082"

certificatesresolvers:
  https-resolver:
    acme:
      email: ${ACME_EMAIL}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
  namecheap:
    acme:
      email: ${ACME_EMAIL}
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /letsencrypt/acme.json
      dnschallenge:
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        provider: namecheap 

  cloudflare:
    acme:
      email: ${ACME_EMAIL}
      storage: /letsencrypt/acme.json
      dnschallenge:
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
          - "8.8.8.8:53"
          - "8.8.4.4:53"
        provider: cloudflare 

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
  file:
    directory: "/etc/traefik/services/"
    watch: true
