apiVersion: 1
contactPoints:
    - orgId: 1
      name: Discord alert
      receivers:
        - uid: aekh80lc9qznka
          type: discord
          settings:
            avatar_url: https://miro.medium.com/v2/da:true/resize:fit:1200/0*ZjYSm_q36J4KChdn
            message: |-
                {{ define "alerts.message" -}}
                  {{ if .Alerts.Firing -}}
                    {{ len .Alerts.Firing }} firing alert(s)
                    {{ template "alerts.summarize" .Alerts.Firing }}
                  {{- end }}
                  {{- if .Alerts.Resolved -}}
                    {{ len .Alerts.Resolved }} resolved alert(s)
                    {{ template "alerts.summarize" .Alerts.Resolved }}
                  {{- end }}
                {{- end }}

                {{ define "alerts.summarize" -}}
                  {{ range . -}}
                  - {{ index .Annotations "summary" }}
                  {{ end }}
                {{ end }}
            title: '{{ template "default.title" . }}'
            url: YOUR-DISCORD-CHANNEL
            use_discord_username: false
          disableResolveMessage: false
