apiVersion: 1
contactPoints:
    - orgId: 1
      name: pagerduty
      receivers:
        - uid: bekha14n1fgu8d
          type: pagerduty
          settings:
            integrationKey: YOUR-PAGERDUTY-KEY 
          disableResolveMessage: false
